version: '3.8'

services:
  youtube-frontend:
    build: .
    ports:
      - "3030:3000"
    volumes:
      - ./cache_data/:/app/.cache
      - ./.env:/app/.env:rw
    restart: unless-stopped
    container_name: youtube-channel-frontend

volumes:
  cache_data:
